# Generated by Django 4.2.23 on 2026-06-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
